import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const resp = await fetch("http://localhost:9999/links", {
    cache: "no-store",
  });
  const links = await resp.json();

  return (
    <html lang="en">
      <body>
        <div>
          <ul className="flex">
            <h1 className="text-2xl mx-5 my-5">
              <Link href={"/"}>조혜영 세미나</Link>
            </h1>
            {links.map((link) => {
              return (
                <li
                  key={link.id}
                  className="flex justify-between gap-x-6 py-5 mx-5"
                >
                  <Link href={link.url} className="">
                    📌 {link.title}
                  </Link>
                </li>
              );
            })}
          </ul>
        </div>

        <div className="mt-5 w-full p-5">
          <div className="border-solid border-2 mx-5 rounded-lg p-5">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
